### ISSUE TITLE
chore: add Summer of Bitcoin

### ISSUE THREAD

**Issue by Anmol-Baranwal** [swapnilsparsh/DevEmpire#260]
## URL

https://www.summerofbitcoin.org/

## Description

- I noticed that this open-source program was missing from the list, so I would like to add it to `components/programs/Programs-Data.js`

> I will be doing this contribution as a part of GSSoC'23.

Please assign me, and I will start contributing towards this issue.

**Comment by swapnilsparsh** [comment]
@Anmol-Baranwal Just adding one program will not grant you any level tag, if you wish to contribute outisde of gssoc then you are free to open a PR direcly without opening a issue. Thank You 🚀

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal Just adding one program will not grant you any level tag, if you wish to contribute outisde of gssoc then you are free to open a PR direcly without opening a issue. Thank You 🚀

Oh, really? Just one program won't grant me any level tag? Well, I guess my 100+ PRs and hard work must have gone unnoticed. Maybe you should take a moment to check my profile and see for yourself. Keep up the constructive feedback! 🚀

**Comment by swapnilsparsh** [comment]
@Anmol-Baranwal There are some rules set by GSSoC that has to be followed, so just adding one program won't grant you any level tag.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal There are some rules set by GSSoC that has to be followed, so just adding one program won't grant you any level tag.

I understand that there are rules set by GSSoC that need to be followed, and I have always adhered to those rules. However, I want to clarify that my contributions extend beyond GSSoC. I am committed to contributing to projects, regardless of the program's duration. I believe in starting small and gradually improving projects to meet high standards. Your statement seems to imply that contributors like me are not valued. As a `Mentor`, `contributor`, and member of the `GSSoC core team`, I have played my part in upholding and forming the program's principles. Have a great day, and I kindly request that you refrain from further replies as I don't want notifications regarding this project.

**Comment by gurjeetsinghvirdee** [comment]
Hey @swapnilsparsh 

I'm writing to you today to express my concern about your recent message to contributors. In your message, you stated that **Just adding one program will not grant you any level tag, if you wish to contribute outside of gssoc then you are free to open a PR direcly without opening a issue.**

I believe that this message was unnecessarily harsh and dismissive. Contributors are giving their time and effort to help improve the project, and they deserve to be treated with respect. Your message sent the message that their contributions are not valued, which is discouraging and demoralizing.

I understand that you may be trying to set expectations for contributors, but there are more constructive ways to do so. For example, you could have simply stated that "In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation."

I urge you to reconsider your approach to communicating with contributors. We all want to see this project succeed, and we can only do that if we work together respectfully and cooperatively.
