### ISSUE TITLE
Footer redesigning

### ISSUE THREAD

**Issue by I-shika** [swapnilsparsh/DevEmpire#317]
I want to redesign footer for an attractive view .

Please assign this issue to me under GSSoC'23.

**Comment by swapnilsparsh** [comment]
@I-shika Can you share some designs ?

**Comment by I-shika** [comment]
yes sure, I will share it by tomorrow.

**Comment by Srishtikumari2002** [comment]
Hey if this issue is not solved yet, so I would like to continue on this issue.
Changes I am willing to make in the footer:
1. Add 2-3 lines about Dev Empire below the 'DevEmpire' word in the footer.
2. Shift all three columns of the footer in the center.
3. Shift the copywrite word(@2023 DevEmpire) at the bottom of the footer along with the GitHub and Twitter logos. like this:
![image](https://github.com/swapnilsparsh/DevEmpire/assets/77767357/6ec4f94a-fd03-472f-9081-18d355724297)

**Comment by I-shika** [comment]
@swapnilsparsh I want to redesign it similar to the below image , without eliminating any component of the previous one and with the original colour theme
![IMG-20230629-WA0041](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/a97372c5-1e27-400b-981c-5ec7b6cddaf9)

**Comment by swapnilsparsh** [comment]
@I-shika Make the footer according to the last image that you have shared by creating all the elements which are shown in the image.

**Comment by I-shika** [comment]
Please don't close this issue I have almost completed it

**Comment by swapnilsparsh** [comment]
@I-shika Sorry to say but as there was no pogress so I have to close this issue

**Comment by I-shika** [comment]
So branch will not get merge?

**Comment by swapnilsparsh** [comment]
@I-shika Please create a new issue, I will assign that and make a new PR
