### ISSUE TITLE
Description of Open Source Programs

### ISSUE THREAD

**Issue by jatiinyadav** [swapnilsparsh/DevEmpire#69]
![Screenshot 2021-10-08 152409](https://user-images.githubusercontent.com/73248007/136536803-d748e777-b87e-42af-b018-d372afa088f2.png)
1. The card in which the heading is coming in `1 line` the description should come in `3 lines`.
2. The card in which the heading is coming in `2 lines` the description should come in  `2 lines`.

**Comment by anil-muraleedharan** [comment]
I would like get a clear explanation on the issue, In the card in which the heading comes in 2 lines we need to reduce the description into max 2 lines right! so how are we planning to do this, should we strip the description to fit in 2 lines or any other ways?

**Comment by anil-muraleedharan** [comment]
I would like to pick this issue please assign it to me, I have tried out the fix for this.
We can do the stripping based on the character length of both header and description. As per my observations heading with `more than 22 characters` are mostly coming in `2 lines` and for containing the description into `2 lines` we have to strip it with `60 characters`. But very rarely this could fail because the font we are using is not a `monospaced` one. I would like to get your opinion on this solution, and suggest if you have any better ideas.
<img width="1341" alt="Screenshot 2021-10-09 at 12 58 40 PM" src="https://user-images.githubusercontent.com/56071561/136648799-3575fa80-1fb9-4fd7-b58c-b1bd229dfcfd.png">

**Comment by swapnilsparsh** [comment]
> I would like to pick this issue please assign it to me, I have tried out the fix for this. We can do the stripping based on the character length of both header and description. As per my observations heading with `more than 22 characters` are mostly coming in `2 lines` and for containing the description into `2 lines` we have to strip it with `60 characters`. But very rarely this could fail because the font we are using is not a `monospaced` one. I would like to get your opinion on this solution, and suggest if you have any better ideas. <img alt="Screenshot 2021-10-09 at 12 58 40 PM" width="1341" src="https://user-images.githubusercontent.com/56071561/136648799-3575fa80-1fb9-4fd7-b58c-b1bd229dfcfd.png">

Work on your idea.
